IN MAI time GIMME localtime LIKE NOW
TODAYS CAN HAZ NOW THING

KILOSECONDS CAN HAZ EASTERBUNNY
PILE CAN HAZ CHEEZBURGER

KILOSECONDS GETZ ANOTHR 3600 OF THOSE TODAYS OWN tm_hour
KILOSECONDS GETZ ANOTHR 60 OF THOSE TODAYS OWN tm_min
KILOSECONDS GETZ ANOTHR PILE OF THOSE TODAYS OWN tm_sec

VISIBLE "OMG IT'S" AND KILOSECONDS SMASHES INTO 1000.0 AND "KILOSECONDS"

BTW http://www.dalkescientific.com/writings/diary/archive/2007/06/01/lolpython.html